In [1]:
import pandas as pd
import numpy as np
 


In [19]:
# 1

array_aleatorio = np.random.randint(0, 101, 10)

print(array_aleatorio)

[13 44 81 92 18 41 42 76  1 49]


In [28]:
#2
# Crear una matriz 5x5 con valores aleatorios en el intervalo [0, 1]
matriz_aleatoria = np.random.rand(5, 5)

print("Matriz Aleatoria:")
print(matriz_aleatoria)

# Encontrar el valor mínimo
valor_minimo = np.min(matriz_aleatoria)

# Encontrar el valor máximo
valor_maximo = np.max(matriz_aleatoria)

# Encontrar la media
valor_media = np.mean(matriz_aleatoria)

print(f"Valor minimo:", valor_minimo)
print(f"Valor Mínimo: {np.min(matriz_aleatoria)}")
print(f"Valor Máximo:", valor_maximo)
print(f"Media:", valor_media)
print(f'Media: {np.mean(matriz_aleatoria)}')


Matriz Aleatoria:
[[0.60960526 0.49536146 0.77622362 0.29256857 0.09218585]
 [0.32163931 0.99153683 0.39303997 0.90629962 0.27862219]
 [0.27183148 0.18561111 0.61925399 0.11547907 0.10456569]
 [0.00589529 0.49823842 0.93241017 0.98089917 0.32642945]
 [0.55705228 0.80442281 0.78192072 0.44589057 0.93990347]]
Valor minimo: 0.0058952945704526805
Valor Mínimo: 0.0058952945704526805
Valor Máximo: 0.9915368316108447
Media: 0.5090754539789639
Media: 0.5090754539789639


In [12]:
# 3
# Crear una matriz de 10 elementos aleatorios en el intervalo [0, 1]
matriz_original = np.random.rand(1, 10)

print("Matriz Original:")
print(matriz_original)

# Crear otra matriz multiplicando por 10 y convirtiendo a enteros
matriz_modificada = (matriz_original * 10).astype(int)

print("\nMatriz Modificada (multiplicada por 10 y convertida a enteros):")
print(matriz_modificada)


Matriz Original:
[[0.74257639 0.50694894 0.02141218 0.29223841 0.87434206 0.8230487
  0.92838579 0.7390758  0.45105989 0.86546158]]

Matriz Modificada (multiplicada por 10 y convertida a enteros):
[[7 5 0 2 8 8 9 7 4 8]]


In [13]:
#4

# Crear una matriz 3x3 con valores aleatorios en el intervalo [0, 9]
matriz = np.random.randint(0, 10, (3, 3))

print("Matriz Original:")
print(matriz)

# Sustituir todos los elementos de la segunda línea por -1
matriz[1, :] = -1

print("\nMatriz Modificada:")
print(matriz)


Matriz Original:
[[1 8 5]
 [6 6 2]
 [7 6 8]]

Matriz Modificada:
[[ 1  8  5]
 [-1 -1 -1]
 [ 7  6  8]]


In [16]:
#5

# Definir los datos
data = {
    'fruta': ['banana', 'maça', 'pera'],
    'preço': [7.90, 10.20, 11.80],
    'quantidade': [12, 3, 4]
}

# Crear el DataFrame
df = pd.DataFrame(data)

# Mostrar el DataFrame
print(df)


    fruta  preço  quantidade
0  banana    7.9          12
1    maça   10.2           3
2    pera   11.8           4
